// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zZSG1C0cmdLuSTwx-wjUHlBr7ujm2W0',
    appId: '1:814311288199:web:eb5e042fc4022bc0333722',
    messagingSenderId: '814311288199',
    projectId: 'pushnotifi-96381',
    authDomain: 'pushnotifi-96381.firebaseapp.com',
    storageBucket: 'pushnotifi-96381.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdvF0zfy58cHOEI1kq34FLI33BnMCtQu8',
    appId: '1:814311288199:android:e049802ea32c1884333722',
    messagingSenderId: '814311288199',
    projectId: 'pushnotifi-96381',
    storageBucket: 'pushnotifi-96381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi_-v_JLEIpHUwlpoT8Hpqdo9xgTg7tMs',
    appId: '1:814311288199:ios:59bdfeeea04d923d333722',
    messagingSenderId: '814311288199',
    projectId: 'pushnotifi-96381',
    storageBucket: 'pushnotifi-96381.appspot.com',
    iosBundleId: 'com.example.pushno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi_-v_JLEIpHUwlpoT8Hpqdo9xgTg7tMs',
    appId: '1:814311288199:ios:59bdfeeea04d923d333722',
    messagingSenderId: '814311288199',
    projectId: 'pushnotifi-96381',
    storageBucket: 'pushnotifi-96381.appspot.com',
    iosBundleId: 'com.example.pushno',
  );
}
